### ISSUE TITLE
debug出现错误

### ISSUE THREAD

**Issue by wxcgeek** [coyove/iis#1]
panic: open config.yml: no such file or directory

goroutine 1 [running]:
github.com/coyove/iis/common.MustLoadConfig()
        /opt/gocode/src/iis-master/common/config.go:56 +0x2ed
main.main()
        /opt/gocode/src/iis-master/main.go:33 +0x13e
exit status 2

**Comment by coyove** [comment]
见一个空的config.yml文件就行
